### ISSUE TITLE
Command-line-options section of website looks...crappy

### ISSUE THREAD

**Issue by kirbyfan64** [gvansickle/ucg#117]
![ucg](https://cloud.githubusercontent.com/assets/1690697/25551304/55d4d476-2c48-11e7-903d-7b77b3d1c1b9.jpg)
Hmmm...that doesn't look right... :O

Also, slight plug but still cool: I made a [Rootbox script](https://github.com/project-rootbox/rootbox-factories/blob/master/general/ucg.sh) that builds ucg...except it's 100% statically linked and runs on pretty much any Linux system: https://www.dropbox.com/s/nc5r5uxv64fnsak/ucg?dl=0

**Comment by gvansickle** [comment]
Hey @kirbyfan64:
Re: the [Rootbox](https://project-rootbox.github.io/guide.html) script: Excellent, thanks!  Looks like you're doing some good work with that project.
Re: the CLI sections of the page: Yeah, I don't know what happened there.  Especially since the first table renders OK.  From what I gather, GitHub has some issues with tables that I've apparently stumbled over.  I'm trying to convert over to a simple Jekyll page (Ask Me How That's Going!(tm)), and hopefully I'll be able to solve that then.

**Comment by kirbyfan64** [comment]
@gvansickle ...which is why I usually either code sites using Sphinx or just do the HTML by myself. Sometimes I end up spending more time getting crud to work than actually working with it...

**Comment by gvansickle** [comment]
> Sometimes I end up spending more time getting crud to work than actually working with it...

Amen brother.  Aaaaaaaa-men.

**Comment by gvansickle** [comment]
Ok @kirbyfan64 , check it out:
https://gvansickle.github.io/ucg/readme/
And I didn't even have to write any Ruby to get it to work (==only half joking).  Closing this as fixed, unless you see any problems on your end.

**Comment by kirbyfan64** [comment]
*opens web page*


Oooooooooh...
