### ISSUE TITLE
HEAD does not containg configure script

### ISSUE THREAD

**Issue by csrabak** [gvansickle/ucg#124]
doing a default cloning of repo brings insuficient code for compiling as the configure script is not available.

**Comment by gvansickle** [comment]
Hi @csrabak : That's intentional and correct.  ./configure is a generated artifact, and hence does not belong under source control.  It gets generated when you do an autoreconf, as is the normal practice with the auto{make,conf} build system.
A "make dist" will generate this file and include it in the generated distributable; this is where you probably have seen an already-existing ./configure file.
Appreciate the report.  Closing with this comment.
