### ISSUE TITLE
any <3 for OSX?

### ISSUE THREAD

**Issue by evandrix** [gvansickle/ucg#71]

**Comment by gvansickle** [comment]
Unfortunately I don't have an OSX system to develop and test against, so probably not in the near future.

**Comment by John-Colvin** [comment]
travis-ci offer OS X testers, so it's possible to use that if you can put up with the slow turnaround.

**Comment by gvansickle** [comment]
I'll look into that, thanks @John-Colvin .

**Comment by sumit0190** [comment]
@gvansickle I haven't looked deeply into the code yet, but would we only have to use getopt instead of argp to get it working on OS X (apart from other minor things, like remove sed -r, ofcourse)? I believe I can help you out with some of those things.

**Comment by gvansickle** [comment]
Hi @sumit0190 ,
I honestly don't know.  I don't want to give up argp and lose the automatic help it generates.  I don't know what other changes might be needed.

**Comment by sumit0190** [comment]
@gvansickle 
I decided to myself that I would hack around to get it running on OSX, and I was able to. There's a bunch of small things that the user would need to do, but nothing that we can't code into the makefile. We will still need to ask the users to install PCRE and standalone-argp using brew, but again, that's not a big deal. I can make these changes if you want me to.

**Comment by gvansickle** [comment]
Hi @sumit0190 ,

Good to hear that there's nothing major in the codebase and/or build system that would need to fundamentally change; I've been trying to keep it as cross-platform as possible, while not having all the platforms I'd like to have available for testing.

I have to plead almost complete ignorance when it comes to all things Apple.  How do FOSS projects generally distribute their apps to Mac users?  Is "brew" the equivalent of yum/dnf in Red Hat/Fedora/etc. and dpkg for Debian/Ubuntu/etc.?  To package things up, would I need a Mac available (maybe this can be done via travis-ci)?  Do I need to go through the "app store", or does Apple allow basically the same type of third-party repo support the Linuxes do?  Can you recommend a link to something on the web like "FOSS Distribution in the Apple Ecosystem for Dummies"?.  I know that last one might sound like a "can you Google this for me?", but I found that finding solid info on how to distribute for various Linux flavors was the hardest part of this whole endeavor (and it's still the most work).

**Comment by John-Colvin** [comment]
Homebrew seems is the preferred package manager for open source developers on OS X these days. There is also macports.

As long as the usual download, untar, configure, make, make install works then it will be trivial to add to homebrew.

**Comment by John-Colvin** [comment]
an example homebrew script for ucg:

```ruby
class Ucg < Formula
  desc "Extremely fast grep-like tool specialized for searching large bodies of source code"
  homepage "https://gvansickle.github.io/ucg/"
  url "https://github.com/gvansickle/ucg/releases/download/0.2.2/universalcodegrep-0.2.2.tar.gz"
  sha256 "dcd8be138ee985014ca247faab81e985ae7cd2f2e84405099c248479a3e9a410"

  depends_on "pcre"
  depends_on "argp-standalone"

  needs :cxx11

  def install
    system "./configure", "--disable-debug",
                          "--disable-dependency-tracking",
                          "--disable-silent-rules",
                          "--prefix=#{prefix}"
    system "make", "install"
  end
end
```

would also need a `test` block to be actually accepted

**Comment by John-Colvin** [comment]
Here's an example `.travis.yml` file to start with:

```yaml
sudo: false

os:
 - osx

install:
 - brew update && brew install pcre argp-standalone

script:
- <shell commands to actually build and test go here>
```

**Comment by sumit0190** [comment]
@gvansickle 
Homebrew is the most common packaging system used by just about every Mac developer. Macports has been waning in popularity over the years, but it still has a following. 
Developing libraries and packages for the Mac typically don't have to go through the App Store, so you can rest easy knowing that packaging UCG for Mac is just a matter of correctly configuring your Makefile and adding some cross-platform handing.
As @John-Colvin suggested, for development and testing, let's just make these small changes first and worry about adding a Homebrew package later. As I had already mentioned, you only need to do a few things to get it to work on a Mac:
1) Install `pcre` and `standalone-argp` using brew
2) Replace all `sed -r` calls with `sed -E`
3) Replace `malloc_stats` with `mstats`, or do away with that function entirely as you suggested in another issue. (Also keep in mind that you need to call configure with a flag to include /usr/include/malloc)
4) When asked for the compiler version, use `sed `to replace all newlines in the input stream (received from g++ -version, for example) with spaces. If you don't do this, `gxx_version_str` in `build_info.cpp` will contain newlines and throw errors.
5) OPTIONAL: You might need to set certain `CPPFLAGS` and `LDFLAGS` in some cases for the linker to correctly recognize the PCRE symbols.

That's all there is to it. I can submit a PR if you want me to.

**Comment by gvansickle** [comment]
Welp, let's get it started!  I pulled a branch for this here: https://github.com/gvansickle/ucg/tree/feature/OSX. I'm starting with @John-Colvin 's .travis.yml and fleshing things out.  @sumit0190 , feel free to send me a PR; Note that I just added a Developer's Certificate of Origin: https://github.com/gvansickle/ucg/blob/master/CONTRIBUTING.md.

**Comment by gvansickle** [comment]
@John-Colvin , @sumit0190 : Well the good news is, I have travis-ci building ucg for Trusty, the not-as-good news is that the OSX build is failing during link.  But I think that's about the last thing I have to get sorted out.

**Comment by sumit0190** [comment]
@gvansickle Would you be able to share the log here so I can take a look? I might have an idea on what's going wrong during the OSX build.

**Comment by kirbyfan64** [comment]
https://travis-ci.org/gvansickle/ucg/jobs/124464159

**Comment by sumit0190** [comment]
Aah, it's exactly as I expected. The PCRE headers and PCRE libraries do not match in the system's default search path. You can get around this by doing something like:
` ./configure CPPFLAGS="-I/usr/local/Cellar/pcre/8.38/include" LDFLAGS="-L/usr/local/Cellar/pcre/8.38/lib"`
or by exporting those variables beforehand.

**Comment by gvansickle** [comment]
@sumit0190 Possibly, but I shouldn't have to.  configure is finding the library:

```
checking lib pcre... (testing)
checking for pcre_study in -lpcre... yes
checking lib pcre... -lpcre
PCRE_LIBS=-lpcre
PCRE_CFLAGS=
checking whether libpcre is new enough... yes, libpcre version = 8.38
```

So it's unclear to me why it could find it there, but not at compile time.  Too tired to beat on this further tonight.....

**Comment by sumit0190** [comment]
Apparently this is a known issue faced by other people as well:
[https://github.com/openresty/openresty/issues/3](https://github.com/openresty/openresty/issues/3)
Anyway, you might wanna try doing that tomorrow to see if it works.

**Comment by gvansickle** [comment]
Oof.  And people accuse Windows of "DLL hell"....

**Comment by gvansickle** [comment]
Ok, so quick status update:
- I've now run about a million travis-ci builds, so much so that GitHub blocked Homebrew access for a time.
- The libpcre problems are the "rpath/LD_LIBRARY_PATH" issue that is the plague of Unii everywhere.  Homebrew installs libpcre into /usr/local/Cellar/pcre/, and autoconf et al has never handled this sort of situation sanely.  I ran into this a few years ago on Ubuntu (I think) with 32 vs. 64 bit libs.  Might be solvable if "brew --something" was able to tell me where it put the library, but so far experiments and Google have come up either wrong or empty on this; in particular, "brew --prefix" and "brew --prefix {lib}prce" are of no use.
- I did get it to compile and run the testsuite with manual CPPFLAGS/LDFLAGS.  I don't know if it was using the correct libpcre shared object at runtime.  The testsuite fails pretty spectacularly, and in ways I can't immediately diagnose.  @sumit0190 , @John-Colvin , anybody: is there a way I can make travis-ci get the test results to me?  E.g. have it tar up the results directory and email it to me?  All I saw was that it could transfer files to Amazon S3, which I'd rather not dink with.
- FYI, here's one of the weirdnesses:

```
19. type_inclusion.at:112: testing User-defined file type specs ...

../../tests/type_inclusion.at:128: ucg --noenv 'include' | wc -l

stderr:

--- -	2016-04-22 02:00:02.000000000 +0000

+++ /Users/travis/build/gvansickle/ucg/build/tests/testsuite.dir/at-groups/19/stdout	2016-04-22 02:00:02.000000000 +0000
@@ -1,2 +1,2 @@
-1
+       0
19. type_inclusion.at:112: 19. User-defined file type specs (type_inclusion.at:112): FAILED (type_inclusion.at:128)
```

So, the test should have output `"1\n"` (one matched line), but it actually output `"       0\n"` (7 spaces, and zero matched lines).  The spaces at least are probably OSX's "wc"'s fault.

Frustrating.  I could really use that PR about now @sumit0190 ;-).  Or better yet an OSX VM.

**Comment by sumit0190** [comment]
@gvansickle I was about to send you a PR, but then I saw that your feature/OSX branch contains almost all the changes that I suggested (except that you didn't determine the OS type and used sed -E in the Makefile). 
I am certain I didn't face the libpcre issue when I built UCG a few days ago, but I can try building it again on a VM this time. I also didn't run the testsuite at all; I'll do that ASAP. I can see from the build results that almost all tests worth running are failing, so maybe I can try to debug these failures on my machine.
Also, I thought `brew info <package>` gives you all possible information related to a package?

**Comment by John-Colvin** [comment]
w.r.t. to homebrew pcre and header locations, they should be available in `/usr/local/lib/` as well as `Cellar`. E.g. on my machine (without all the `share` stuff, for clarity):
```
% find /usr/local -name \*pcre\*
/usr/local/bin/pcre-config
/usr/local/bin/pcregrep
/usr/local/bin/pcretest
/usr/local/Cellar/pcre
/usr/local/Cellar/pcre/8.38/bin/pcre-config
/usr/local/Cellar/pcre/8.38/bin/pcregrep
/usr/local/Cellar/pcre/8.38/bin/pcretest
/usr/local/Cellar/pcre/8.38/include/pcre.h
/usr/local/Cellar/pcre/8.38/include/pcre_scanner.h
/usr/local/Cellar/pcre/8.38/include/pcre_stringpiece.h
/usr/local/Cellar/pcre/8.38/include/pcrecpp.h
/usr/local/Cellar/pcre/8.38/include/pcrecpparg.h
/usr/local/Cellar/pcre/8.38/include/pcreposix.h
/usr/local/Cellar/pcre/8.38/lib/libpcre.1.dylib
/usr/local/Cellar/pcre/8.38/lib/libpcre.a
/usr/local/Cellar/pcre/8.38/lib/libpcre.dylib
/usr/local/Cellar/pcre/8.38/lib/libpcre16.0.dylib
/usr/local/Cellar/pcre/8.38/lib/libpcre16.a
/usr/local/Cellar/pcre/8.38/lib/libpcre16.dylib
/usr/local/Cellar/pcre/8.38/lib/libpcre32.0.dylib
/usr/local/Cellar/pcre/8.38/lib/libpcre32.a
/usr/local/Cellar/pcre/8.38/lib/libpcre32.dylib
/usr/local/Cellar/pcre/8.38/lib/libpcrecpp.0.dylib
/usr/local/Cellar/pcre/8.38/lib/libpcrecpp.a
/usr/local/Cellar/pcre/8.38/lib/libpcrecpp.dylib
/usr/local/Cellar/pcre/8.38/lib/libpcreposix.0.dylib
/usr/local/Cellar/pcre/8.38/lib/libpcreposix.a
/usr/local/Cellar/pcre/8.38/lib/libpcreposix.dylib
/usr/local/Cellar/pcre/8.38/lib/pkgconfig/libpcre.pc
/usr/local/Cellar/pcre/8.38/lib/pkgconfig/libpcre16.pc
/usr/local/Cellar/pcre/8.38/lib/pkgconfig/libpcre32.pc
/usr/local/Cellar/pcre/8.38/lib/pkgconfig/libpcrecpp.pc
/usr/local/Cellar/pcre/8.38/lib/pkgconfig/libpcreposix.pc
/usr/local/include/pcre.h
/usr/local/include/pcre_scanner.h
/usr/local/include/pcre_stringpiece.h
/usr/local/include/pcrecpp.h
/usr/local/include/pcrecpparg.h
/usr/local/include/pcreposix.h
/usr/local/lib/libpcre.1.dylib
/usr/local/lib/libpcre.a
/usr/local/lib/libpcre.dylib
/usr/local/lib/libpcre16.0.dylib
/usr/local/lib/libpcre16.a
/usr/local/lib/libpcre16.dylib
/usr/local/lib/libpcre32.0.dylib
/usr/local/lib/libpcre32.a
/usr/local/lib/libpcre32.dylib
/usr/local/lib/libpcrecpp.0.dylib
/usr/local/lib/libpcrecpp.a
/usr/local/lib/libpcrecpp.dylib
/usr/local/lib/libpcreposix.0.dylib
/usr/local/lib/libpcreposix.a
/usr/local/lib/libpcreposix.dylib
/usr/local/lib/pkgconfig/libpcre.pc
/usr/local/lib/pkgconfig/libpcre16.pc
/usr/local/lib/pkgconfig/libpcre32.pc
/usr/local/lib/pkgconfig/libpcrecpp.pc
/usr/local/lib/pkgconfig/libpcreposix.pc
/usr/local/Library/LinkedKegs/pcre
/usr/local/Library/Taps/homebrew/homebrew-core/Aliases/pcre1
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/pcre++.rb
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/pcre.rb
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/pcre2.rb
/usr/local/opt/pcre
```

**Comment by gvansickle** [comment]
> w.r.t. to homebrew pcre and header locations, they should be available in /usr/local/lib/ as well as Cellar.

They're not though.  Homebrew has pcre as a "keg_only" package apparently, and hence leaves it unlinked and only under /usr/local/Cellar/...etc.  There's a libpcre already installed on the travis-ci VM at /usr/local/, but it for some reason is missing at least one function I'm using.  Hence the need for some sort of rpath-based solution.

**Comment by gvansickle** [comment]
So here's me, thinking that if I set up a FreeBSD (PC-BSD actually) VM, that'd at least be closer to OSX than anything I've tested on locally so far.  O.M.G.  I can't even get programs to link to libstdc++ without a manual "-Wl,rpath" and/or LD_LIBRARY_PATH silliness.  Not been a fun weekend.  I was able to work around some of the different tool behaviors though (wc -l == 7 spaces, then the line count), so I guess there's that.

**Comment by sumit0190** [comment]
@gvansickle Any tips for debugging the test failures? The logs aren't that helpful.

**Comment by gvansickle** [comment]
@sumit0190 Yeah, tell me about it. ;-)  Are you talking about the logs on Travis-CI, or were you able to run "make check" as you mentioned [above](https://github.com/gvansickle/ucg/issues/71#issuecomment-213412886)?  From the former, I guess the best lead is this failure:

```
UniversalCodeGrep search modifier checks
 11: '--ignore-case' and '--word-regexp' combos      ok
 12: --literal vs. --word-regexp vs. --ignore-case   ok
 13: --[no]smart-case                                FAILED (search_modifiers.at:101)
```

Those results make no sense.  11 and 12 passing means that all kinds of matching variations were tested and passed, yet the default-on "--smart-case" for some bizarre reason fails only on Macs:

```
#                             -*- compilation -*-
13. search_modifiers.at:92: testing --[no]smart-case ...
../../tests/search_modifiers.at:101: ucg --noenv 'abc' | wc -l | tr -d '\t \r\n'
stderr:
--- -	2016-04-26 08:03:57.000000000 +0000
+++ /Users/travis/build/gvansickle/ucg/build/tests/testsuite.dir/at-groups/13/stdout	2016-04-26 08:03:57.000000000 +0000
@@ -1 +1 @@
-3
+0
13. search_modifiers.at:92: 13. --[no]smart-case (search_modifiers.at:92): FAILED (search_modifiers.at:101)
```

... EXCEPT IS DOESN'T, because some of the tests in 11 won't pass if --smart-case isn't working.  Ugh.

Is it silently crashing for some reason?  If you can run the testsuite locally, you can do like it says and go into the tests/testsuite.dir/nn/ directories and run the `run` script to rerun the test, and see if it gives you any more clues.  You can run the whole testsuite as discussed here: http://www.gnu.org/software/autoconf/manual/autoconf.html#testsuite-Invocation.  The ‘--verbose’, '--debug', and '--trace' options could be useful.

One dumb question: OSX isn't still using old Mac '\r' line ending character, is it?  That could cause some havok.

BTW: There are a couple errors in there that I do know the cause of.  Some of the tests use the `script` utility; of course, its command line differs significantly enough from the Linux one that those tests break on that, so ignore any of those for now.

**Comment by gvansickle** [comment]
> One dumb question: OSX isn't still using old Mac '\r' line ending character, is it?

O.M.G.  That might somehow be it.  I just downloaded the "raw" log from travis-ci and guess what?  Yep, CR line endings on the file.  Now supposedly OSX, and particularly the Unix tools, have been using \n-only for some time according to the Internet(tm), but maybe something never got the word?

**Comment by gvansickle** [comment]
Ok, this is interesting:

```
$ otool -L ucg
ucg:
	/usr/local/opt/pcre/lib/libpcre.1.dylib (compatibility version 4.0.0, current version 4.6.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
The command "otool -L ucg" exited with 0.
```

I did not expect to be picking up libpcre under /usr/local/opt/.  In fact, I'm trying to explicitly set rpath at link time to the Homebrew directory.  @sumit0190 , @John-Colvin , @anybody, what do you guys make of this?

**Comment by sumit0190** [comment]
That is weird indeed; I wonder if this has something to do with the Homebrew libpcre package. I do remember seeing plenty of issues with it.
Regardless, we still don't know why so many tests fail. I don't think the line endings are the culprits here; OSX hasn't seen '\r' since ages now. And running `make check` and examining the logs isn't great help. You think it would be easier to just place breakpoints at important lines and examine the input stream at that instant to figure out what's the reason behind the incorrect output?

**Comment by gvansickle** [comment]
> That is weird indeed; I wonder if this has something to do with the Homebrew libpcre package. I do remember seeing plenty of issues with it.  Regardless, we still don't know why so many tests fail.

Well, if it's linking to the wrong library, which it looks like it is, I'm certain that's a major part of the problem.  I just don't understand how it's picking up that particular one when (AFAICT) I'm literally hardcoding the runtime path to pick up the Homebrew one.  [Why. Does. Every. Moment. Have. To. Be. So. Hard.](https://getyarn.io/yarn-clip/0a3ab0e5-deaa-49e7-8550-cd2df08a7636/gif)

> You think it would be easier to just place breakpoints at important lines and examine the input stream at that instant to figure out what's the reason behind the incorrect output?

Definitely.  If you're able to get this on a debugger, run it with one of the failing tests.  Or, try this, as it doesn't depend on files generated and then deleted by Autotest:
- Download the Boost source tarball.  I've been using 1.58.0, but it doesn't really matter which version, it's just a large amount of source code to search.
- Untar it into a directory at the same level as the ucg source root.  I.e.:
`~/src/ucg` ==> Root of ucg working copy,
`~/src/boost_1_58_0` ==> Root of Boost extracted tarball.
- Then set the debugger up with a command line like `ucg --noenv 'BOOST.*HPP' ~/src/boost_1_58_0`.

Set a breakpoint at `main()` and step through it until something fails.  Try different params and regexes if you don't get a failure on the first try.  I wish I could give you more detail on what to look for, but like I said, the test logs don't make much sense; the above is what I'd be doing now if I had access to a real OSX machine/VM/acct.

Let me know what you see with `otool -L ucg` too; if that's different that might be a clue.

From my isolated end here, I think what I'll do is granularize the test suite better; each printed line item actually represents a number of tests (usually variations of options and/or regexes), only one of which needs to fail to cause the whole test case to fail (and then the rest of the tests aren't even run).  That might help narrow things down some, and would be an improvement for all platforms.

**Comment by John-Colvin** [comment]
Might have mentioned this before, but just in case:
Homebrew installs to Cellar but also links/copies to /usr/local. You should
pretty much never have to specify paths in to Cellar directly unless you're
dealing with a package that is "keg only", which I'm pretty sure libpcre is
not.
On 28 Apr 2016 2:17 pm, "Gary R. Van Sickle" <notifications@github.com>
wrote:

That is weird indeed; I wonder if this has something to do with the
Homebrew libpcre package. I do remember seeing plenty of issues with it.
Regardless, we still don't know why so many tests fail.

Well, if it's linking to the wrong library, which it looks like it is, I'm
certain that's a major part of the problem. I just don't understand how
it's picking up that particular one when (AFAICT) I'm literally hardcoding
the runtime path to pick up the Homebrew one. Why. Does. Every. Moment.
Have. To. Be. So. Hard.
<https://getyarn.io/yarn-clip/0a3ab0e5-deaa-49e7-8550-cd2df08a7636/gif>

You think it would be easier to just place breakpoints at important lines
and examine the input stream at that instant to figure out what's the
reason behind the incorrect output?

Definitely. If you're able to get this on a debugger, run it with one of
the failing tests. Or, try this, as it doesn't depend on files generated
and then deleted by Autotest:

   - Download the Boost source tarball. I've been using 1.58.0, but it
   doesn't really matter which version, it's just a large amount of source
   code to search.
   - Untar it into a directory at the same level as the ucg source root.
   I.e.: ~/src/ucg ==> Root of ucg working copy, ~/src/boost_1_58_0 ==>
   Root of Boost extracted tarball.
   - Then set the debugger up with a command line like ucg --noenv
   'BOOST.*HPP' ~/src/boost_1_58_0.

Set a breakpoint at main() and step through it until something fails. Try
different params and regexes if you don't get a failure on the first try. I
wish I could give you more detail on what to look for, but like I said, the
test logs don't make much sense; the above is what I'd be doing now if I
had access to a real OSX machine/VM/acct.

Let me know what you see with otool -L ucg too; if that's different that
might be a clue.

From my isolated end here, I think what I'll do is granularize the test
suite better; each printed line item actually represents a number of tests
(usually variations of options and/or regexes), only one of which needs to
fail to cause the whole test case to fail (and then the rest of the tests
aren't even run). That might help narrow things down some, and would be an
improvement for all platforms.

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/gvansickle/ucg/issues/71#issuecomment-215419828>

**Comment by gvansickle** [comment]
> Might have mentioned this before, but just in case:
> Homebrew installs to Cellar but also links/copies to /usr/local. You should
> pretty much never have to specify paths in to Cellar directly unless you're
> dealing with a package that is "keg only", which I'm pretty sure libpcre is
> not.

Hi @John-Colvin ,
Right, you did mention that.  Homebrew's pcre lib is in fact either keg_only (which I think is the case, but I can't recall now why I think that), and/or gets overridden by the libpcre that is already installed on the OSX instances Travis-CI is giving me.  And either way, having it link to `/usr/local/opt/pcre/lib/libpcre.1.dylib` when I'm rpathing it to Homebrew is at this point simply baffling.

**Comment by gvansickle** [comment]
Ok, so there is this:
`brew --prefix pcre=/usr/local/opt/pcre`
I swear that wasn't there before.

**Comment by gvansickle** [comment]
Ok, so it looks like `OSX`'s `fts` library is broken: https://travis-ci.org/gvansickle/ucg/jobs/126811742

We should be seeing output like this in there:

```
Considering file: ../src/sync_queue_impl_selector.h
... normal file.
... should be scanned.
```

So painful.

**Comment by gvansickle** [comment]
AAAAAAnd got it:

```
## ------------- ##
## Test results. ##
## ------------- ##
ERROR: 21 tests were run,
3 failed (1 expected failure).
4 tests were skipped.
## -------------------------- ##
## testsuite.log was created. ##
## -------------------------- ##
```

I know what the three failures are (the thing with BSD `script` I mentioned earlier).  Now I just need to M4/sh around that issue, clean things up a lot, and with any luck OSX will have a new source code searching utility soon.

**Comment by gvansickle** [comment]
So there's this:
https://travis-ci.org/gvansickle/ucg/builds/127120058

And also the test suite passes on PC-BSD.  Yeah, I'm awesome.  ;-)

**Comment by sumit0190** [comment]
Whoa. So what was behind the failing tests?

**Comment by gvansickle** [comment]
@sumit0190 Long story, but it boiled down to two things:
- The Globber class wasn't finding any files.  This was because it was using the `fts` interface to traverse directory trees and passing the FTS_NOSTAT option.  OSX (at least on the HFS+ filesystem) isn't able to determine regular files without the stat, so they get returned as FTS_NSOK / 11 / "no stat(2) requested", which I was (more or less intentionally) ignoring.  On Linux and Cygwin, I do get FTS_F (regular) files from it even without this flag, so that's why I didn't notice it before.  I'll have to evaluate any performance impact on these platforms due to this change, but so far it looks like it's minor/none.  And it is more correct.
- The `script` thing.  **O.M.G.**  So, for some of the tests, I need to trick `ucg` into thinking it's outputting to a terminal, even though its output is really going to a file.  The `script` utility does that quite easily.  Great, except its command line syntax is different between Linux&Cygwin/OSX/*BSD (at least the current PC-BSD).  So I had to write my own "`script` flavor detector" in configure.ac, and a wrapper for it in the testsuite scripts.  The former went ok.  The latter started out as an `m4` nightmare, then I gave up and wrote a straight `sh` function replacement.  That all ran fine on Cygwin and PC-BSD, but then the detection broke on OSX.  So another few rounds and that was fixed, so that now, Linux and Cygwin use one "flavor", and OSX and BSD use another, all wrapped in a `sh` function.

There's a bunch of cleanup left to do, but I should be able to merge this into `master` in the next few days.

**Comment by gvansickle** [comment]
@sumit0190 , @John-Colvin , @evandrix , @kirbyfan64 , OSX/PC-BSD support is now in trunk!  Currently, you'll have to roll your own, and I'm working on a Wiki entry on that right now, but it's what's in the .travis.yml file.
Try it out and let me know what you think, report issues here, etc.
Thanks everyone for the help and encouragement!

**Comment by sumit0190** [comment]
Awesome! I'll try it out tonight and report back! Thank YOU for all the hard work.

**Comment by gvansickle** [comment]
Ok, OS X build instructions are here: https://github.com/gvansickle/ucg/wiki#experimental-os-x-support.
