### ISSUE TITLE
malloc_stats() is unportable

### ISSUE THREAD

**Issue by 0-wiz-0** [gvansickle/ucg#97]
src/MemDiags.cpp calls malloc_stats(), which is a GNU extension and does not exist e.g. on NetBSD.
Please only use it on Linux, e.g. by wrapping it in `#ifdef __linux__`.

**Comment by gvansickle** [comment]
Hi @0-wiz-0 ,
I'm guessing you're reporting this against the 0.2.2 tarball?    Somebody else reported this a while back (#72), and that whole file has been removed since 0f2b1ca67b1d08f618b9897e3928a296c1c0fe93.  Definitely see [here](https://github.com/gvansickle/ucg/wiki) if you're trying to get ucg working on a BSD; there were a large number of portability improvements made a while back to get ucg running on OSX and FreeBSD, so you'll definitely want to pick up the current trunk.
...And I guess I should change the "experimental support" to "is supported" on that page.
...And it's probably past time that I roll another release.

**Comment by 0-wiz-0** [comment]
Yes, I filed that bug report against 0.2.2. I looked for `malloc_stats` in issues, but not for the file name. Good that this is already resolved.
And yes, I'd appreciate a release :-)
Thanks!
